### PR TITLE
Stylingattempt2

### PR DESCRIPTION
**Pull request by vanessaconti**
sorry i finished late but i finally got it according to the readme instructions, made a few changes to snack details according to requirements in tests and to make a little more appealing on index page, didnt get to finish css in rest of the app but i would like to if you still want to collaborate maybe over the weekend or in spare time, we can talk ty dylan, pls lmk if there are any issues/merge conflicts

### CODE REVIEW

**Comment by vanessaconti** [comment]
edited because forgot to change base branch to dev for pull request...

**Comment by vanessaconti** [comment]
added more changes to pass more tests fyi, will keep going and use different branch for testing

**Comment by DylanLovell93** [comment]
Very well done! Pages look great. The index and show test are failing because they are asking for very specific things (specific css class names, and specific html tags like h4 and article). And the new form test are failing because we didn't add an image input for the form. Small things imo. Well done!

**Comment by DylanLovell93** [comment]
I'm going to put this through to dev and then to main for deployment since I've already tested it

**Pull request merged**
